### ISSUE TITLE
Running tyr_service

### ISSUE THREAD

**Issue by stuartlynn** [valhalla/tyr#102]
Hey all 

I had successfully built a docker container (https://github.com/stuartlynn/valhalla-docker) for valhalla which seemed to work pretty well. I am trying to update it now to support the changes from tyr_simple_service changing to tyr_service 

I am running the server using 

```tyr_service /data/valhalla/valhalla.json```

with valhalla.json being identical to the one in the conf repo. It seems to start with no errors but when I try and access it on port 8002 I get no response. Is something changed in the way that tyr works or am I running the service wrong?

Would love any help you can give.

**Comment by kevinkreiser** [comment]
Hey @stuartlynn we moved `tyr_simple_service` (which runs all the parts of the distributed service in one process) to the `tools` repo (since it has a lot of dependencies). So for minimal extra work you can simply clone and build the `tools` repo to get `tyr_simple_service` and use that as you had been before.

`tyr_service` is a single process that handles the serialization of route responses only, it cannot function alone, and requires you to run other processes that pass it things from upstream. It looks like this: prime_httpd -> loki_service -> thor_service -> odin_service -> tyr_service.

I feel you may be obviating the need for elaboration of this in our docs! Basically `tyr_simple_service` encapsulates all of these other processes into a single one so you dont have the complex process of running all these processes.

You may be thinking to yourself, why would I ever want to run so many processes, what a configuration pain. Yes, its a configuration pain but it gives you two important properties.

The first one is redundancy, in that you can run more than one of each process and if one goes down, there are others to handle requests. When you bundle all these processes as threads in a single process and one crashes, the whole thing bites the dust, game over. 

The second reason we allow running in this way is for the sake of load balancing. As you might have guessed, some parts of the request get fulfilled at different parts of the *pipeline* described above. You might also notice that some parts seem *heavier* than others. Based on which parts need more time/resources, we choose to run more or less processes for a given part of the pipeline. Some of this is described in very general terms here: https://github.com/kevinkreiser/prime_server#the-point

**Comment by stuartlynn** [comment]
Wondeful! Thank you for the reply. Have it working in the docker container again. I think the set up you have is pretty good. I like the modularity! The docker container lets me run locally with ease which is nice. 

Thanks for the help getting this fixed
