### ISSUE TITLE
Weird route

### ISSUE THREAD

**Issue by costales** [valhalla/tyr#114]
Hi!
From ~5 days ago, this route is different (50km instead of 33km):
http://www.openstreetmap.org/directions?engine=mapzen_car&route=43.3060%2C-5.6876%3B43.5325%2C-5.6613#map=11/43.4090/-5.6192

A few meters more and the route is OK (33km):
http://www.openstreetmap.org/directions?engine=mapzen_car&route=43.3037%2C-5.6893%3B43.5325%2C-5.6613#map=11/43.4159/-5.6927

Thanks in advance!

**Comment by dnesbitt61** [comment]
We will take a look. I can't think of any recent code change that would cause this - perhaps an OSM data change occurred. Either way we will see if we can figure it out. Thanks.

**Comment by dnesbitt61** [comment]
Looks like these ways (maybe others near there?) are the issue:
https://www.openstreetmap.org/way/176100084
https://www.openstreetmap.org/way/407986936

They used to be highway=tertiary until 3 days ago. 

This changes set seems to be where the changes occurred. Basically once we traverse from neighborhood streets onto arterial roads we don't like to transition down to prevent cutting through neightborhoods as shortcuts. I can try some algorithm adjustments if needed, but my opinion is that this road looks like it is a collector/arterial road rather than residential. Will defer to your opinion there since you know the area.

**Comment by costales** [comment]
Thanks a lot @dnesbitt61 
My opinion is not to invert time on this :)
Thanks a lot for your support!! Mapzen is the best!
