### ISSUE TITLE
 Navigation guides wrong way though one way road 

### ISSUE THREAD

**Issue by costales** [valhalla/tyr#116]
Hi!
One [user found this issue](https://bugs.launchpad.net/unav/+bug/1568504). Probably will be the OSM data, but I'd like to report it.

In this route:
http://www.openstreetmap.org/directions?engine=mapzen_car&route=50.1074%2C8.6634%3B48.8972%2C8.7025#map=18/48.91024/8.71867&layers=Q

In this point of the route:

![route](https://cloud.githubusercontent.com/assets/5886786/14536556/48f33874-0273-11e6-8cfd-ac65c54bf042.png)

The indication is in the wrong way.

Thanks in advance!

**Comment by dgearhart** [comment]
Might be our hierarchy - since it works properly on shorter route
![screenshot from 2016-04-14 13 35 32](https://cloud.githubusercontent.com/assets/7515853/14537707/1f2cf656-0246-11e6-8429-5411fc8a5b23.png)

**Comment by dnesbitt61** [comment]
This is a code issue but should be pretty rare. Isolated to an issue with correlating EdgeInfo to shortcut edges. Since the 2 shortcut edges are the same length between the 2 nodes where this road becomes singly digitized there is ambiguity over which EdgeInfo (and shape) is selected. Fix is being tested - use length plus number of shape points to lessen the chance of ambiguity (though not 100% foolproof it does fix this case). Will push a fix for the data producers soon.

**Comment by dnesbitt61** [comment]
This is now fixed in production. Thanks for reporting this bug.

**Comment by costales** [comment]
Thanks a lot :)
